# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('repeat', models.BooleanField(default=False)),
                ('expire_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('signals_text', models.TextField()),
            ],
        ),
    ]
