# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vertex',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
