# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20160913_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vertex',
            options={'ordering': ('label',)},
        ),
        migrations.RemoveField(
            model_name='vertex',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='vertex',
            name='register_time',
            field=models.BigIntegerField(default=time.time),
        ),
    ]
