# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160920_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vertex',
            old_name='register_time',
            new_name='last_seen',
        ),
    ]
