# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20160921_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vertex',
            old_name='active',
            new_name='enabled',
        ),
    ]
